// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogFilePath() {
  return window['go']['app']['App']['GetLogFilePath']();
}

export function GetWindowSize() {
  return window['go']['app']['App']['GetWindowSize']();
}

export function LoadWindowState() {
  return window['go']['app']['App']['LoadWindowState']();
}

export function LogDebug(arg1) {
  return window['go']['app']['App']['LogDebug'](arg1);
}

export function LogError(arg1) {
  return window['go']['app']['App']['LogError'](arg1);
}

export function LogInfo(arg1) {
  return window['go']['app']['App']['LogInfo'](arg1);
}

export function LogWarning(arg1) {
  return window['go']['app']['App']['LogWarning'](arg1);
}

export function MaximiseApp() {
  return window['go']['app']['App']['MaximiseApp']();
}

export function MinimiseApp() {
  return window['go']['app']['App']['MinimiseApp']();
}

export function OpenLogFile() {
  return window['go']['app']['App']['OpenLogFile']();
}

export function QuitApp() {
  return window['go']['app']['App']['QuitApp']();
}

export function ReloadApp() {
  return window['go']['app']['App']['ReloadApp']();
}

export function SaveWindowState() {
  return window['go']['app']['App']['SaveWindowState']();
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['app']['App']['SetWindowSize'](arg1, arg2);
}
