// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetLogFilePath():Promise<string>;

export function GetWindowSize():Promise<number|number>;

export function LoadWindowState():Promise<app.WindowState>;

export function LogDebug(arg1:string):Promise<void>;

export function LogError(arg1:string):Promise<void>;

export function LogInfo(arg1:string):Promise<void>;

export function LogWarning(arg1:string):Promise<void>;

export function MaximiseApp():Promise<void>;

export function MinimiseApp():Promise<void>;

export function OpenLogFile():Promise<void>;

export function QuitApp():Promise<void>;

export function ReloadApp():Promise<void>;

export function SaveWindowState():Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;
