// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAgentLoadouts(arg1) {
  return window['go']['main']['StorageAPI']['LoadAgentLoadouts'](arg1);
}

export function LoadData(arg1) {
  return window['go']['main']['StorageAPI']['LoadData'](arg1);
}

export function LoadSettings(arg1) {
  return window['go']['main']['StorageAPI']['LoadSettings'](arg1);
}

export function LoadTemplates(arg1) {
  return window['go']['main']['StorageAPI']['LoadTemplates'](arg1);
}

export function LoadUserData(arg1, arg2) {
  return window['go']['main']['StorageAPI']['LoadUserData'](arg1, arg2);
}

export function SaveAgentLoadouts(arg1, arg2) {
  return window['go']['main']['StorageAPI']['SaveAgentLoadouts'](arg1, arg2);
}

export function SaveData(arg1, arg2) {
  return window['go']['main']['StorageAPI']['SaveData'](arg1, arg2);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['StorageAPI']['SaveSettings'](arg1, arg2);
}

export function SaveTemplates(arg1, arg2) {
  return window['go']['main']['StorageAPI']['SaveTemplates'](arg1, arg2);
}

export function SaveUserData(arg1, arg2, arg3) {
  return window['go']['main']['StorageAPI']['SaveUserData'](arg1, arg2, arg3);
}
