// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAgentLoadouts(arg1:string):Promise<string>;

export function LoadData(arg1:string):Promise<string>;

export function LoadSettings(arg1:string):Promise<string>;

export function LoadTemplates(arg1:string):Promise<string>;

export function LoadUserData(arg1:string,arg2:string):Promise<string>;

export function SaveAgentLoadouts(arg1:string,arg2:string):Promise<void>;

export function SaveData(arg1:string,arg2:any):Promise<void>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function SaveTemplates(arg1:string,arg2:string):Promise<void>;

export function SaveUserData(arg1:string,arg2:string,arg3:any):Promise<void>;
