// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAgentLoadouts() {
  return window['go']['main']['StorageAPI']['LoadAgentLoadouts']();
}

export function LoadData(arg1) {
  return window['go']['main']['StorageAPI']['LoadData'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['StorageAPI']['LoadSettings']();
}

export function LoadTemplates() {
  return window['go']['main']['StorageAPI']['LoadTemplates']();
}

export function SaveAgentLoadouts(arg1) {
  return window['go']['main']['StorageAPI']['SaveAgentLoadouts'](arg1);
}

export function SaveData(arg1, arg2) {
  return window['go']['main']['StorageAPI']['SaveData'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['StorageAPI']['SaveSettings'](arg1);
}

export function SaveTemplates(arg1) {
  return window['go']['main']['StorageAPI']['SaveTemplates'](arg1);
}
