// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadAgentLoadouts():Promise<string>;

export function LoadData(arg1:string):Promise<string>;

export function LoadSettings():Promise<string>;

export function LoadTemplates():Promise<string>;

export function SaveAgentLoadouts(arg1:string):Promise<void>;

export function SaveData(arg1:string,arg2:any):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SaveTemplates(arg1:string):Promise<void>;
