// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function DownloadUpdateWithProgress(arg1:string,arg2:any):Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function InstallUpdate(arg1:string):Promise<void>;

export function OpenDownloadFolder():Promise<void>;
