// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['UpdateAPI']['CheckForUpdates']();
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['UpdateAPI']['DownloadUpdate'](arg1);
}

export function DownloadUpdateWithProgress(arg1, arg2) {
  return window['go']['main']['UpdateAPI']['DownloadUpdateWithProgress'](arg1, arg2);
}

export function GetCurrentVersion() {
  return window['go']['main']['UpdateAPI']['GetCurrentVersion']();
}

export function InstallUpdate(arg1) {
  return window['go']['main']['UpdateAPI']['InstallUpdate'](arg1);
}

export function OpenDownloadFolder() {
  return window['go']['main']['UpdateAPI']['OpenDownloadFolder']();
}
