// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMainData() {
  return window['go']['main']['ValorantAPI']['GetMainData']();
}

export function GetOwnedItems(arg1) {
  return window['go']['main']['ValorantAPI']['GetOwnedItems'](arg1);
}

export function GetPlayerLoadout() {
  return window['go']['main']['ValorantAPI']['GetPlayerLoadout']();
}

export function GetPlayerUUID() {
  return window['go']['main']['ValorantAPI']['GetPlayerUUID']();
}

export function GetPreGameMatch() {
  return window['go']['main']['ValorantAPI']['GetPreGameMatch']();
}

export function GetPreGamePlayer() {
  return window['go']['main']['ValorantAPI']['GetPreGamePlayer']();
}

export function SetPlayerLoadout(arg1) {
  return window['go']['main']['ValorantAPI']['SetPlayerLoadout'](arg1);
}
