// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMainData():Promise<main.MainData>;

export function GetOwnedItems(arg1:string):Promise<main.OwnedItemsResponse>;

export function GetPlayerLoadout():Promise<main.PlayerLoadoutResponse>;

export function GetPlayerUUID():Promise<string>;

export function GetPreGameMatch():Promise<main.PreGameMatchResponse>;

export function GetPreGamePlayer():Promise<main.PreGamePlayerResponse>;

export function SetPlayerLoadout(arg1:main.PlayerLoadoutResponse):Promise<main.PlayerLoadoutResponse>;
